### ISSUE TITLE
Production environment not loading js asset when using Typescript as input

### ISSUE THREAD

**Issue by turansadri** [WP-Performance/presswind-plugin#1]
I'm using the Press-wind starter theme and I noticed that when using TypeScript as input (changing `main.js` to `main.ts` in vite.config.js) the production does not enqueue the built js asset in front end.

I did set the `is_ts` option to `true` but the problem seems to be on PWVite.php on line 214. `set_script_prod` function only checks if the `src` in manifest.json contains `.js` but as the input is main.ts the `src` value is `main.ts`.

I'm not sure if this should be fixed in `set_script_prod` or should I be able to fix this in my vite.config.js so that it will print `main.js` as `src` in manifest.json when I'm running the build?

Here's how my manifest.json looks like after building:

```
{
  "main.ts": {
    "css": [
      "assets/main-tpLjbuv5.css"
    ],
    "file": "assets/main-DMYVO1Dv.js",
    "isEntry": true,
    "src": "main.ts"
  }
}
```

**Comment by ipatate** [comment]
hi, i have tested with .ts file and it's work normally. 
the child theme for my test https://github.com/WP-Performance/child-2024-presswind
